### PR TITLE
make hppc a valid OSGI bundle

### PR DESCRIPTION
**Pull request by gdelafosse**
add the maven-bundle-plugin to make hppc-collections a valid OSGI bundle

### CODE REVIEW

**Comment by gdelafosse** [comment]
Hello
would you accept this pull request?
It's just a matter of executing the maven-bundle-plugin while packaging the jar. Only the MANIFEST file will be modified with some OSGI specific entries...

**Comment by dweiss** [comment]
No need to post to the list. We had problems with OSGi plugins in the past (causing numerous build reiterations). I don't know if this has been solved. I'll look into it.

**Comment by dweiss** [comment]
Ok, I can include it. The problem is that HPPC produces two artefacts, not one ({{hppc-0.8.0-SNAPSHOT-esoteric.jar}}, {{hppc-0.8.0-SNAPSHOT.jar}}) and only the latter contains OSGi metadata. If you know how to fix it, please update the PR, add {{CHANGES.txt}} entry and I'll pull it in.

**Comment by gdelafosse** [comment]
hppc-0.8.0-SNAPSHOT-esoteric.jar has now the OSGI Manifest entries

**Comment by dweiss** [comment]
Argh. maven-bundle-plugin screws up exclusion/ inclusion of classes in maven-jar-plugin (esoteric jar contains the same content as the primary jar). Do you know how to handle this?

**Comment by vsonnier** [comment]
@dweiss Hi ! I've encountered the same problem in HPPC-RT. The solution is to use the `bundle-manifest` goal to only generate the manifest file, and let the `jar` plugin make the packaging as usual:
````
   <!-- Add Manifest OSGIs info to the future Jar -->
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <executions>
                    <!-- HPPCRT-48: Prepare OSGI data to be included by the regular maven-jar-plugin, DO NOT use the bundle goal ! -->
                    <execution>
                        <id>bundle-manifest</id>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>manifest</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            
            <!-- Build main artifact --> 
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <!-- HPPCRT-48: Must "manually" add OSGI manifest to a regular Jar data, because bundle packaging apparently cannot filter class-wise -->  
                            <archive>  
                                <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                            </archive> 
                            <excludes>
                              <exclude>**/KType*</exclude>
                              <exclude>**/*KType*</exclude>
                              <exclude>**/VType*</exclude>
                              <exclude>**/*VType*</exclude>
                              <exclude>**/Intrinsics*</exclude>
                             </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
````

**Comment by dweiss** [comment]
Ah... Thanks Vincent! I may look into it again then (just removed the whole thing out of frustration).

**Pull request merged**
